apiVersion: v1
kind: Service
metadata:
  name: project2-service
spec:
  selector:
    app: projectpod
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
#  clusterIP: 10.0.171.239
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 192.0.2.127